### ISSUE TITLE
Transcript to STDOUT?

### ISSUE THREAD

**Issue by astrowonk** [freedmand/textra#1]
It would be very convenient if textra could display the output to STDOUT, via some optional command line argument. 

This would make it easier to say, use with python `subprocess` to automate running it on images and then capture the text to a string (which we could then use programmatically however one likes.)

It's not hard to work around and just use the file system for this, but it would make it a little easier.

**Comment by freedmand** [comment]
Working on adding this feature in. Thanks for the feedback!

**Comment by astrowonk** [comment]
> Working on adding this feature in. Thanks for the feedback!

Thank you! We have been going back-and-forth on Mastodon, so I appreciate your efforts! looking forward to the next release; my fork is a bit of a hack. 😂

**Comment by freedmand** [comment]
Closed with latest release!
