### ISSUE TITLE
2023-03-24 13:33:04.515 textra[46484:13310980] Required assets are not available for Locale:en-US ERROR: Speech recognizer does not support on-device recognition

### ISSUE THREAD

**Issue by crystoneme** [freedmand/textra#5]
Textra a mp3 audio file, come across the following mistake:

2023-03-24 13:33:04.515 textra[46484:13310980] Required assets are not available for Locale:en-US
ERROR: Speech recognizer does not support on-device recognition

**Comment by rolandcrosby** [comment]
I just encountered the same issue. Turns out you need to enable Siri and dictation in system settings for the speech recognition feature to work. It would be nice if this were documented in the readme.

**Comment by alecglassford** [comment]
To drill down a little on the preceding comment: I was able to get this working by enabling dictation (**Keyboard** --> **Dictation**) in **System Settings**, while leaving Siri disabled.

Interestingly, flipping the **Dictation** switch didn't immediately fix the error to me, but maybe it would have if I'd restarted my terminal, or something like that, to propagate the change (?? just guessing).

What did work immediately was just clicking **Start Dictation** in the **Edit** menu from my terminal and following the prompts. After that, textra runs without error.

So my suggested quick fix for anyone who encounters this error is to just do **Edit** --> **Start Dictation** in your terminal (which also enables the **Dictation** setting system-wide). Then, if you later want to disable dictation, do so in **System Settings** --> **Keyboard** --> **Dictation**.

(This all, presumably, only works on [Macs with Apple Silicon](https://support.apple.com/en-us/HT211814), per #4.)

**Comment by freedmand** [comment]
Thanks for flagging! I'd welcome a code change to help provide a more descriptive error message, potentially with a solution as in #4 — I probably won't be able to get to it for a while. In the meantime, I'm going to add a section to the readme. Also hi @alecglassford, long time! I hope you're doing well! 👋
