### ISSUE TITLE
locale support?

### ISSUE THREAD

**Issue by ogomez92** [freedmand/textra#8]
HEllo,
I get the following error when trying to convert some file. I think it might be because either my system locale is set to Spanish (probably) or because the file that I tried to convert was in Spanish. Any hints? The system should have locale resources installed, or does this recognizer only work when system is set to English?

2023-04-03 15:20:48.276 textra[54391:4225664] Required assets are not available for Locale:es_ES
ERROR: Speech recognizer does not support on-device recognition

**Comment by alecglassford** [comment]
@ogomez92 Does https://github.com/freedmand/textra/issues/5#issuecomment-1489042478 address the problem?

**Comment by ogomez92** [comment]
Ah yes, I didn't see that other issue due to it having the entire log message as the title. Thanks.
